.\" Manpage for aur_helper.sh.                                                  
.\" Create a pull request or issue on github.com/mikelpint/arch-scripts to correct errors or typos.

'\" t                                                                     
.\"     Title: aur_helper.sh                              
.\"     Author: Mikel Pintado (see AUTHORS for more information) 
.\"     Date: 2018-05-11                                                 
.\"    Manual: Pacman Manual                                              
.\"    Source: arch-scripts 0.1                                              
.\"  Language: English                                                    
.\"                                                                       

.TH "AUR_HELPER.SH" "8" "2018\-05\-11" "aur_helper.sh 0\&.1" "AUR_HELPER.SH Manual"

.SH NAME
    aur_helper.sh \- Install an AUR helper 

.SH SYNOPSIS
    aur_helper <operation> [target]

.SH DESCRIPTION
    aur_helper is a shell scripts that provides an easy way to install an AUR helper.

.SH OPERATIONS
    help, h
        Open this manpage.
    install, i
        Install one of the available AUR helpers. See TARGETS for more information.
    uninstall, u
        Uninstall one of the supported AUR helpers. See TARGETS for more information.

.SH TARGETS
    Available AUR helpers:
        * trizen
        * aura
        * yay

.SH OTHER
    I recommend running this program as normal user. However, you will need to have sudo permission.

.SH AUTHOR
    Mikel Pintado (github.com/mikelpint)
